// Seed topic lists so the topic filter/admin form has useful options
// even before any questions have been imported yet. These follow the
// IB syllabus subject guides. Feel free to edit/extend as needed.
module.exports = {
  'Math AA': [
    'Number and Algebra',
    'Functions',
    'Geometry and Trigonometry',
    'Statistics and Probability',
    'Calculus',
  ],
  'Math AI': [
    'Number and Algebra',
    'Functions',
    'Geometry and Trigonometry',
    'Statistics and Probability',
    'Calculus',
  ],
  Physics: [
    'Measurements and Uncertainties',
    'Mechanics',
    'Thermal Physics',
    'Waves',
    'Electricity and Magnetism',
    'Circular Motion and Gravitation',
    'Atomic, Nuclear and Particle Physics',
    'Energy Production',
    'Wave Phenomena (HL)',
    'Fields (HL)',
    'Electromagnetic Induction (HL)',
    'Quantum and Nuclear Physics (HL)',
  ],
  Chemistry: [
    'Stoichiometric Relationships',
    'Atomic Structure',
    'Periodicity',
    'Chemical Bonding and Structure',
    'Energetics/Thermochemistry',
    'Chemical Kinetics',
    'Equilibrium',
    'Acids and Bases',
    'Redox Processes',
    'Organic Chemistry',
    'Measurement and Analysis',
    'Additional Higher Level (AHL)',
  ],
  Biology: [
    'Cell Biology',
    'Molecular Biology',
    'Genetics',
    'Ecology',
    'Evolution and Biodiversity',
    'Human Physiology',
    'Nucleic Acids (HL)',
    'Metabolism, Cell Respiration and Photosynthesis (HL)',
    'Plant Biology (HL)',
    'Genetics and Evolution (HL)',
    'Animal Physiology (HL)',
  ],
  Economics: [
    'Introduction to Economics',
    'Microeconomics',
    'Macroeconomics',
    'The Global Economy',
  ],
};
